Food.create(name:"にんじん" , fod: 1, category_id: 1)
Food.create(name:"玉ねぎ" , fod: 1, category_id: 1)
Food.create(name:"きゅうり" , fod: 2, category_id: 1)
Food.create(name:"トマト" , fod: 2, category_id: 1)
Food.create(name:"水" , fod: 1, category_id: 2)
Food.create(name:"レモンジュース" , fod: 1, category_id: 2)
Food.create(name:"牛乳" , fod: 2, category_id: 2)
Food.create(name:"コーラ" , fod: 2, category_id: 2)

# Category.create(name:"野菜")
# Category.create(name:"飲料水")